### ISSUE TITLE
Prevent moveme if the user is already in an AutoHost lobby

### ISSUE THREAD

**Issue by kieve** [tsbreuer/IRCAutoHost#10]
If I understand the issue correctly:
Attempting to move a player that is already in a lobby to another lobby may cause them to end up in the abyss.
This kinda falls under https://github.com/kieve/IRCAutoHost/issues/7, but expands to tracking users separately from their lobby.
If they're in some other multiplayer lobby, we can't really detect that... so this would be limited tracking people in AutoHost lobbies only.

**Comment by tsbreuer** [comment]
It is not only autohost lobbies, but any lobby, so yeah, we can only limit this from autohost lobbies. 
A possible fix is to kick the player from the lobby he is in before moving him finally into the new one.

**Comment by tsbreuer** [comment]
this issue was solved by the new "Invite" method. Invites dont cause this issue.
