### ISSUE TITLE
Consider skipping a map if the map has been taken down

### ISSUE THREAD

**Issue by chong601** [tsbreuer/IRCAutoHost#11]
(Not sure if this is related to issue #6, close this if it is covered in that issue).

When a user (idk if AutoHost checks the map is downloadable before selecting a random map) added a map that had been taken down (like [this map](https://osu.ppy.sh/s/288950)), AutoHost will select that map, causing all users to issue a `!skip` command in order to skip the map.

It is pretty rare to encounter this issue, but would be nice if it can automatically skip it.

**Comment by tsbreuer** [comment]
TODO: skip directly instead of asking lobby to skip.

**Comment by tsbreuer** [comment]
This was fixed on one of the commits some time ago while  i was working the beatmap error exception. Maps now will be checked, and if its not 100% right, it wont switch and will ask the lobby to input for a new map or tell it to try again.
