### ISSUE TITLE
Time format for "Max length" message is not very good.

### ISSUE THREAD

**Issue by kieve** [tsbreuer/IRCAutoHost#12]
Let's say the lobby max length is 6 minutes.
If you try to add a map longer than that, it will tell you that the max length is 6 minutes, but it's formatted like this:
6:0

It should be formatted
6:00

**Comment by tsbreuer** [comment]
Doing a string format, should be pretty easy. Theres a few on the code on pp showing

**Comment by kieve** [comment]
Total misclick closing that...
Anyways, we should just have a few Utility classes for formatting stuff. So it ends up being formatted consistently everywhere.

**Comment by tsbreuer** [comment]
This was fixed some commits ago to MM:SS
