### ISSUE TITLE
Race in the !moveme command.

### ISSUE THREAD

**Issue by kieve** [tsbreuer/IRCAutoHost#4]
When using the command `!info`, you will get a list of lobbies.
It will be numbered.
So, you send the command `!moveme <lobby number>`.
Now, let's say that before you send the `!moveme` command somebody creates a new lobby.
The number you saw before may not be correct anymore. You might get put in the wrong lobby.
This is random, since a hash map is being used for the collection of lobbies.

**Comment by tsbreuer** [comment]
Might need to do a bit of overhaul to the way lobbies are stored to fix this. weill keep an eye on.

**Comment by tsbreuer** [comment]
Fixed in IRCAutoHost 4734124
